repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
      - id: pt_structure
  - repo: https://github.com/mondeja/pre-commit-po-hooks
    rev: 'v1.7.3'
    hooks:
      - id: untranslated-messages
        files: '\.po$'
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        types: [file]
        files: '^(src|stubs|tests).*\.py'
        additional_dependencies:
          - flake8-bugbear==24.2.6
          - flake8-comprehensions==3.14.0
          - flake8-noqa==1.4.0
          - flake8-pyi==24.1.0
          - flake8-type-checking==2.9.1
  - repo: local
    hooks:
      - id: system
        name: bandit
        entry: ./bandit.sh
        language: system
        # NOTE: We want this hook to always run, but exactly once
        #       instead of for every file. So we exclude all files
        exclude: '.*'
        always_run: true
        pass_filenames: false
      - id: system
        name: mypy
        entry: ./mypy.sh
        language: system
        # NOTE: We want this hook to always run, but exactly once
        #       instead of for every file. So we exclude all files
        exclude: '.*'
        always_run: true
        pass_filenames: false
      - id: system
        name: check-setup-cfg
        entry: |
          bash -c 'FILES=$(git diff --cached --name-only);
          echo "Debug - Files changed: $FILES";
          if echo "$FILES" | grep "setup.cfg" > /dev/null; then
            if echo "$FILES" | grep "requirements.txt" > /dev/null; then
              echo "✅ setup.cfg and requirements.txt both modified - looks good!";
              exit 0;
            else
              echo "⚠️  Warning: setup.cfg was modified but requirements.txt was not!";
              echo "If you have added new dependencies, you need to run \"make compile\" to re-generate the requirements.txt. Otherwise, you can ignore thi warning";
              exit 1;
            fi;
          fi'
        language: system
        pass_filenames: false
