repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
      - id: pt_structure
  - repo: https://github.com/mondeja/pre-commit-po-hooks
    rev: 'v1.7.3'
    hooks:
      - id: untranslated-messages
        files: '\.po$'
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        types: [file]
        files: '^(src|stubs|tests).*\.py'
        additional_dependencies:
          - flake8-bugbear==24.2.6
          - flake8-comprehensions==3.14.0
          - 'flake8-markupsafe@git+https://github.com/vmagamedov/flake8-markupsafe@b391bd13df9330e01666d304b7f4403d67e5ceba'
          - flake8-noqa==1.4.0
          - flake8-pyi==24.1.0
          - flake8-type-checking==2.9.0
  - repo: local
    hooks:
      - id: system
        name: bandit
        entry: ./bandit.sh
        language: system
        # NOTE: We want this hook to always run, but exactly once
        #       instead of for every file. So we exclude all files
        exclude: '.*'
        always_run: true
        pass_filenames: false
      - id: system
        name: mypy
        entry: ./mypy.sh
        language: system
        # NOTE: We want this hook to always run, but exactly once
        #       instead of for every file. So we exclude all files
        exclude: '.*'
        always_run: true
        pass_filenames: false
