from zope.interface import classImplements, Interface

class IException(Interface): ...
class IStandardError(IException): ...
class IWarning(IException): ...
class ISyntaxError(IStandardError): ...
class ILookupError(IStandardError): ...
class IValueError(IStandardError): ...
class IRuntimeError(IStandardError): ...
class IArithmeticError(IStandardError): ...
class IAssertionError(IStandardError): ...
class IAttributeError(IStandardError): ...
class IDeprecationWarning(IWarning): ...
class IEOFError(IStandardError): ...
class IEnvironmentError(IStandardError): ...
class IFloatingPointError(IArithmeticError): ...
class IIOError(IEnvironmentError): ...
class IImportError(IStandardError): ...
class IIndentationError(ISyntaxError): ...
class IIndexError(ILookupError): ...
class IKeyError(ILookupError): ...
class IKeyboardInterrupt(IStandardError): ...
class IMemoryError(IStandardError): ...
class INameError(IStandardError): ...
class INotImplementedError(IRuntimeError): ...
class IOSError(IEnvironmentError): ...
class IOverflowError(IArithmeticError): ...
class IOverflowWarning(IWarning): ...
class IReferenceError(IStandardError): ...
class IRuntimeWarning(IWarning): ...
class IStopIteration(IException): ...
class ISyntaxWarning(IWarning): ...
class ISystemError(IStandardError): ...
class ISystemExit(IException): ...
class ITabError(IIndentationError): ...
class ITypeError(IStandardError): ...
class IUnboundLocalError(INameError): ...
class IUnicodeError(IValueError): ...
class IUserWarning(IWarning): ...
class IZeroDivisionError(IArithmeticError): ...

classImplements(Exception, IException)
classImplements(Warning, IWarning)
classImplements(SyntaxError, ISyntaxError)
classImplements(LookupError, ILookupError)
classImplements(ValueError, IValueError)
classImplements(RuntimeError, IRuntimeError)
classImplements(ArithmeticError, IArithmeticError)
classImplements(AssertionError, IAssertionError)
classImplements(AttributeError, IAttributeError)
classImplements(DeprecationWarning, IDeprecationWarning)
classImplements(EOFError, IEOFError)
classImplements(EnvironmentError, IEnvironmentError)
classImplements(FloatingPointError, IFloatingPointError)
classImplements(IOError, IIOError)
classImplements(ImportError, IImportError)
classImplements(IndentationError, IIndentationError)
classImplements(IndexError, IIndexError)
classImplements(KeyError, IKeyError)
classImplements(KeyboardInterrupt, IKeyboardInterrupt)
classImplements(MemoryError, IMemoryError)
classImplements(NameError, INameError)
classImplements(NotImplementedError, INotImplementedError)
classImplements(OSError, IOSError)
classImplements(OverflowError, IOverflowError)
classImplements(ReferenceError, IReferenceError)
classImplements(RuntimeWarning, IRuntimeWarning)
classImplements(StopIteration, IStopIteration)
classImplements(SyntaxWarning, ISyntaxWarning)
classImplements(SystemError, ISystemError)
classImplements(SystemExit, ISystemExit)
classImplements(TabError, ITabError)
classImplements(TypeError, ITypeError)
classImplements(UnboundLocalError, IUnboundLocalError)
classImplements(UnicodeError, IUnicodeError)
classImplements(UserWarning, IUserWarning)
classImplements(ZeroDivisionError, IZeroDivisionError)
