from types import ModuleType

def resolve_asset_spec(spec: str, pname: str = '__main__') -> tuple[str | None, str]: ...
def asset_spec_from_abspath(abspath: str, package: ModuleType) -> str: ...
def abspath_from_asset_spec(spec: str, pname: str = '__main__') -> str: ...
