from pyramid.interfaces import IRequest

def get_csrf_token(request: IRequest) -> str: ...
def new_csrf_token(request: IRequest) -> str: ...
def check_csrf_token(request: IRequest, token: str = 'csrf_token', header: str = 'X-CSRF-Token', raises: bool = True) -> bool: ...
def check_csrf_origin(request: IRequest, *, trusted_origins: list[str] | None = None, allow_no_origin: bool = False, raises: bool = True) -> bool: ...
