from typing import Any

from pyramid.interfaces import IRequest, IRouter
from pyramid.scripting import AppEnvironment

def setup_logging(config_uri: str, global_conf: dict[str, Any] | None = None) -> None: ...
def get_app(config_uri: str, name: str | None = None, options: dict[str, Any] | None = None) -> IRouter: ...
def get_appsettings(config_uri: str, name: str | None = None, options: dict[str, Any] | None = None) -> dict[str, Any]: ...
def bootstrap(config_uri: str, request: IRequest | None = None, options: dict[str, Any] | None = None) -> AppEnvironment: ...
