from collections.abc import Iterable

def asbool(s: object) -> bool: ...
def aslist_cronly(value: str | Iterable[str]) -> list[str]: ...
def aslist(value: str | Iterable[str], flatten: bool = True) -> list[str]: ...
