from privatim.i18n import _

cantons_named = [
    ('AG', _('Aargau')),
    ('AI', _('Appenzell Innerrhoden')),
    ('AR', _('Appenzell Ausserrhoden')),
    ('BE', _('Bern')),
    ('BL', _('Basel-Landschaft')),
    ('BS', _('Basel-Stadt')),
    ('FR', _('Fribourg')),
    ('GE', _('Geneva')),
    ('GL', _('Glarus')),
    ('GR', _('Graubünden')),
    ('JU', _('Jura')),
    ('LU', _('Lucerne')),
    ('NE', _('Neuchâtel')),
    ('NW', _('Nidwalden')),
    ('OW', _('Obwalden')),
    ('SG', _('St. Gallen')),
    ('SH', _('Schaffhausen')),
    ('SO', _('Solothurn')),
    ('SZ', _('Schwyz')),
    ('TG', _('Thurgau')),
    ('TI', _('Tessin')),
    ('UR', _('Uri')),
    ('VD', _('Waadt')),
    ('VS', _('Valais')),
    ('ZG', _('Zug')),
    ('ZH', _('Zürich')),
]

CANTONS_SHORT = [
    ('AG', 'AG'),
    ('AI', 'AI'),
    ('AR', 'AR'),
    ('BE', 'BE'),
    ('BL', 'BL'),
    ('BS', 'BS'),
    ('FR', 'FR'),
    ('GE', 'GE'),
    ('GL', 'GL'),
    ('GR', 'GR'),
    ('JU', 'JU'),
    ('LU', 'LU'),
    ('NE', 'NE'),
    ('NW', 'NW'),
    ('OW', 'OW'),
    ('SG', 'SG'),
    ('SH', 'SH'),
    ('SO', 'SO'),
    ('SZ', 'SZ'),
    ('TG', 'TG'),
    ('TI', 'TI'),
    ('UR', 'UR'),
    ('VD', 'VD'),
    ('VS', 'VS'),
    ('ZG', 'ZG'),
    ('ZH', 'ZH'),
]
